const Sequelize   =  require ("sequelize");
const path        =  require ("path");
const db          =  require(path.join(__dirname ,"../", "sequelize-db"));

module.exports = db.define ("Event" ,{
   venue_title:Sequelize.TEXT ,
   guestlist_count: Sequelize.INTEGER ,
   venue_id: Sequelize.INTEGER ,
   tickets_URL: Sequelize.TEXT ,
   guestlist_conditions: Sequelize.TEXT ,
   description: Sequelize.TEXT ,
   closed_message: Sequelize.TEXT ,
   ticket_sales_count: Sequelize.INTEGER ,
   home_URL: Sequelize.TEXT ,
   friendly_id : Sequelize.TEXT ,
   get_friendly_id : Sequelize.TEXT ,
   customizable_ad_banner_image_href: Sequelize.TEXT ,
   template_active: Sequelize.TEXT ,
   max_guests_per_guestlist: Sequelize.INTEGER ,
   customizable_ad_banner_destination_url: Sequelize.TEXT ,
   ticket_redemptions_count: Sequelize.INTEGER ,
   show_in_calendars: Sequelize.TEXT ,
   guestlist_URL: Sequelize.TEXT ,
   time: Sequelize.TEXT ,
   parent_id: Sequelize.INTEGER ,
   open: Sequelize.TEXT ,
   pass_codes: Sequelize.TEXT ,
   public_reservations: Sequelize.TEXT ,
   public_guestlists: Sequelize.TEXT ,
   notes: Sequelize.TEXT ,
   active: Sequelize.BOOLEAN ,
   flyers: Sequelize.JSON ,
   tag_list: Sequelize.JSON ,
   restaurant_mode: Sequelize.TEXT ,
   tickets_sold_count: Sequelize.INTEGER ,
   reservation_count: Sequelize.INTEGER ,
   wiki_name: Sequelize.TEXT ,
   reservations_count: Sequelize.INTEGER ,
   repeat_day: Sequelize.TEXT ,
   max_number_of_guests: Sequelize.INTEGER ,
   cover: Sequelize.TEXT ,
   title: Sequelize.TEXT ,
   id: {type : Sequelize.INTEGER , primaryKey : true} ,
   created_at: Sequelize.TEXT ,
   canceled: Sequelize.TEXT ,
   VIP_URL: Sequelize.TEXT ,
   artist_event: Sequelize.JSON ,
   flyer_url: Sequelize.TEXT ,
   venue_passes_active: Sequelize.TEXT ,
   updated_at: Sequelize.TEXT ,
   template: Sequelize.TEXT ,
   ages: Sequelize.TEXT ,
   myspace_URL: Sequelize.TEXT ,
   let_taxable: Sequelize.TEXT ,
   date: Sequelize.DATE ,
   dayOfTheWeek: Sequelize.INTEGER ,
   close: Sequelize.TEXT ,
   short_description: Sequelize.TEXT ,
   headliner: Sequelize.INTEGER
})
