import { OnInit } from '@angular/core';
import { Http } from '@angular/http';
import { DragulaService } from 'ng2-dragula';
import 'rxjs/Rx';
import { Observable } from 'rxjs/Observable';
export declare class DataService implements OnInit {
    private http;
    private dragulaService;
    current: any;
    availableTypes: any;
    sites: any;
    constructor(http: Http, dragulaService: DragulaService);
    ngOnInit(): void;
    postToServer(action: string, data: any, h: Array<any>): Observable<any>;
    userRole(): Promise<{}>;
    save(data?: any, next?: (data: any) => null): void;
    newSite(data: any, next: any): void;
    saveCell(cell: any): Promise<{}>;
    uploadFile(data: any, domain: any): Promise<{}>;
    parseFileFields(data: any, domain?: boolean): Promise<{}>;
    newField(data: any): any;
    find(path: any, ref?: any): any;
    get(itemType: any, itemID: any): Promise<{}>;
    select(itemType: any, itemID: any): Promise<{}>;
    unselect(): void;
    selected(): any;
    getSitesList(): Promise<{}>;
    parseTypes(): void;
    post(path: Array<number>, newData: any): void;
    update(path: Array<number>, newData: any): void;
    findParent(path: any): any;
    destroy(path: any): void;
    calculatePaths(path?: Array<number>, ref?: any): void;
}
